services:
  app:
    build: .
    container_name: linkly
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
    command: uvicorn linkly.main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:4.4  # Use 5+ if AVX is supported on your system
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped

volumes:
  mongo-data:
  redis_data:
