version: '3.8'

services:
  mongodb:
  # image version chai aafno mergi le change garehunxa, 
  # AVX unsupported system haru ko lagi vanerea you 4.4 garako ho
  # yadi timro system ma AVX support garxa vane recommend to use >= 5 version hai.
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
